### PR TITLE
bug when set capacity : if head < tail we have nil values when dequeu…

### PR DESCRIPTION
**Pull request by fredmurdoc**
…e. Insertion off nil values after head and before tail, some unit tests to fix

### CODE REVIEW

**Comment by zealws** [comment]
Thanks @fredmurdoc, looks good to me!

**Comment by zealws** [comment]
Hmm. So I ran the tests a few times after merging your PR, and it looks like one of the tests now transiently fails with this stack-trace (happens maybe 10% of the time).

```
# go test
panic: runtime error: slice bounds out of range [161:158]

goroutine 787 [running]:
github.com/zealws/golang-ring.(*Ring).extend(0xc000068480, 0x9e)
        /home/zeal/go/src/github.com/zealws/golang-ring/ring.go:196 +0x72d
github.com/zealws/golang-ring.(*Ring).SetCapacity(0xc000068480, 0x9e)
        /home/zeal/go/src/github.com/zealws/golang-ring/ring.go:34 +0x7d
github.com/zealws/golang-ring.TestConcurrency.func1(0xc000068480, 0xc0000122c0, 0x302)
        /home/zeal/go/src/github.com/zealws/golang-ring/ring_test.go:218 +0x1c7
created by github.com/zealws/golang-ring.TestConcurrency
        /home/zeal/go/src/github.com/zealws/golang-ring/ring_test.go:196 +0xbd
exit status 2
FAIL    github.com/zealws/golang-ring   0.025s
```

I don't have time to dig into the failure right now, but I'd prefer not to leave master broken until I get a chance, so I'm going to revert the commit.

If you can debug and fix before I get a chance, I'll accept the updates, otherwise I'll try to fix it and get a commit up with your changes and a fix sometime in the next few days.

Sorry for not catching this before merging!

**Comment by fredmurdoc** [comment]
Hello thanks for your feedback !
It's strange, i have ran under Windows and Linux with go 1.15
All it's good : 
```
~/go/src$ go test -timeout 30s -run '^(TestSetsSize|TestSavesSomeData|TestCapacity|TestCapacityWithOverflow|TestReusesBuffer|TestOverflowsBuffer|TestPartiallyOverflows|TestPeeks|TestConstructsArr|TestContentSize|TestConcurrency)$' github.com/fredmurdoc/golang-ring

ok      github.com/fredmurdoc/golang-ring`
```

```
~/go/src/github.com/fredmurdoc/golang-ring$ go test
PASS
ok      github.com/fredmurdoc/golang-ring       0.066s
```

**Comment by zealws** [comment]
Yeah, as I mentioned, it's transiently failing. I did some further tests using this command to run the tests 100 times and only print the PASS/FAIL line with a count:

```
# for i in `seq 100` ; do go test ; done | grep -oE '(PASS|FAIL)' | sort | uniq -c
     12 FAIL
     88 PASS
```

The test fails about 10-15% of the time.

**Comment by zealws** [comment]
Ok, I figured out why the test was failing. `TestConcurrency` just does a bunch of random actions to a Ring object concurrently.

If you are shrinking the capacity (by calling `SetCapacity` with a size smaller than the current size) **and** the `tail` is in the part that gets cut off, then the code that rearranges the slices will panic.

This happens consistently if this condition is hit, but due to the random nature of `TestConcurrency` that only appears to happen about 10% of the time.

I'm gonna refactor the `extend` function a bit to fix the bug you reported and the case the ring gets shortened and should get a fix up shortly. :)

**Comment by zealws** [comment]
Ok, [this commit](https://github.com/zealws/golang-ring/commit/7c86fdb43134a32961f75b40a4875b06365bf951) includes your changes, fixes the bug when shrinking the buffer, and some unit-tests that test the condition triggering the bug you uncovered.

Also I ran the tests 1000 times just to make sure there's no other issue with the changes. They're pretty fast, so it only took a few minutes.

Thanks for the contribution! I appreciate it! :smiley:

**Pull request merged**
